---
# from: https://docs.flutter.dev/get-started/install/linux/android?tab=download#install-the-flutter-sdk

- name: Create download directory
  ansible.builtin.file:
    path: "{{ download_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  become: true

- name: Download Flutter SDK
  ansible.builtin.get_url:
    url: "{{ flutter_sdk_download_url }}"
    dest: "{{ download_dir }}/{{ flutter_sdk_file_name }}"

- name: Unarchive
  ansible.builtin.unarchive:
    src: "{{ download_dir }}/{{ flutter_sdk_file_name }}"
    dest: /usr/bin
    remote_src: yes
  become: true

- name: Add Flutter to your PATH
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    regexp: "{{ flutter_path_line_regex }}"
    line: "{{ flutter_path_line }}"
    create: true
  loop:
  - .bashrc
  - .bash_profile
  - .profile

