---
# from: https://docs.flutter.dev/get-started/install/linux/android

- name: OS specific
  include_tasks: "{{ ansible_os_family }}/{{ ansible_distribution }}/main.yml"

- name: Flutter Doctor
  include_tasks: flutter doctor.yml
  when: run_flutter_doctor